### ISSUE TITLE
How do I assign strong to the header?

### ISSUE THREAD

**Issue by EmmaJLussier** [EmmaJLussier/plan-a-website#3]
![Screen Shot 2021-03-07 at 11 06 18 AM](https://user-images.githubusercontent.com/77282460/110246352-4a365100-7f35-11eb-8b51-2e335c146b69.png)

**Comment by EmmaJLussier** [comment]
@hellachella @raven-rhea

**Comment by EmmaJLussier** [comment]
@hellachella @raven-rhea
I'm almost done I am just having trouble with the strong tag
![Screen Shot 2021-03-07 at 12 14 36 PM](https://user-images.githubusercontent.com/77282460/110248408-eadd3e80-7f3e-11eb-950f-08eb0859b19a.png)

**Comment by raven-rhea** [comment]
So your missing the word Berries directly inside of the header. The site should look like this in the browser, because "Berries" isn't the H1 its wrapped in a strong tag
<img width="649" alt="Screen Shot 2021-03-07 at 12 35 46 PM" src="https://user-images.githubusercontent.com/55094082/110249037-ef572680-7f41-11eb-9644-1d879686e86f.png">
